### ISSUE TITLE
Unable to Install Update

### ISSUE THREAD

**Issue by JustAnNormalPerson** [davidwhitman/SMOL#86]
So I have the Update downloaded but whenever I try to install it the application shuts off.

**Comment by wispborne** [comment]
@JustAnNormalPerson a few things things to try.
- First, SMOL is supposed to close when you hit Install, then bring up a new console window to do the installation, then you need to open SMOL again when it's done. I'm guessing the console window doesn't appear?
- Delete smol-update.zip, then restart SMOL to redownload it.
- Run SMOL as an admin in case it's failing because of a permissions issue.
- Do a manual update by opening up smol-update.zip and extracting the files inside, overwriting any that are already there. There'll be a folder called `files` and then a bunch of folders, but if you click through them then you'll find the ones at the end that need to go into your SMOL folder.

**Comment by wispborne** [comment]
I have on my to-do list to make a nice, standalone updater so it's easy to run in case it doesn't get launched from SMOL for whatever reason, but it's not done yet...

**Comment by JustAnNormalPerson** [comment]
Thanks for the quick reply!
